import resend

from app.config import settings


def send_security_report(
    recipient_email: str,
    subject: str,
    report: str,
) -> dict:
    """
    Send a SentinelForge security report by email.
    """

    if not settings.resend_api_key:
        raise ValueError(
            "RESEND_API_KEY is not configured."
        )

    resend.api_key = settings.resend_api_key

    response = resend.Emails.send(
        {
            "from": settings.email_from,
            "to": [recipient_email],
            "subject": subject,
            "html": f"""
            <html>
                <body>
                    <h2>🛡️ SentinelForge AI Security Report</h2>

                    <p>
                        Your security analysis report is ready.
                    </p>

                    <hr>

                    <pre style="
                        white-space: pre-wrap;
                        font-family: Arial, sans-serif;
                    ">{report}</pre>

                    <hr>

                    <p>
                        This report was generated by
                        SentinelForge AI.
                    </p>
                </body>
            </html>
            """,
        }
    )

    return response